'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Maklumat_Pemohon_Menunggu
    
    '''<summary>
    '''navigation_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navigation_menu As Global.QuartersManagement.navigation_menu
    
    '''<summary>
    '''maklumat_pemohon_menunggu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maklumat_pemohon_menunggu As Global.QuartersManagement.maklumat_pemohon_menunggu
End Class
