'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class maklumat_permohonan

    '''<summary>
    '''permohonanBaharu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanBaharu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTarikhBaharu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhBaharu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''permohonanMenunggu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanMenunggu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTarikhMenuggu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhMenuggu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''permohonanKeputusan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanKeputusan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTarikhKeputusan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhKeputusan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPangkat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPangkat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoTentera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTentera As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNama As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJantina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJantina As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikhLahir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhLahir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatusKahwin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusKahwin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMulaBerkhidmat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMulaBerkhidmat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTamatBerkhidmat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTamatBerkhidmat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJenisTempatTinggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenisTempatTinggal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikhMulaMenetap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhMulaMenetap As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblMaklumatAnak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMaklumatAnak As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblKuarterDipohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKuarterDipohon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikhPermohonan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhPermohonan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trUnitDitawarkan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUnitDitawarkan As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trTarikhMasuk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTarikhMasuk As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblTarikhMasuk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhMasuk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnField As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''MsgTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''strlbl_top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_top As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SaveFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveFunction As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Refresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Refresh As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mvMaklumatStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvMaklumatStatus As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''tbSebabBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSebabBatal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBatalPermohonan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatalPermohonan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divSuratTawaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuratTawaran As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnTerimaTawaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTerimaTawaran As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTolakTawaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTolakTawaran As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvSenaraiKuarters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSenaraiKuarters As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnTerimaCadangan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTerimaCadangan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTolakCadangan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTolakCadangan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSebabDitolak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSebabDitolak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSebabDibatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSebabDibatal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MsgBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''strlbl_bottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_bottom As Global.System.Web.UI.WebControls.Label
End Class
