'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pendaftaran_penjawat
    
    '''<summary>
    '''MsgTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''strlbl_top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_top As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SaveFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveFunction As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''Refresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Refresh As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''txtNoPekerja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoPekerja As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlJawatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJawatan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNamaPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamaPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCawangan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCawangan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlJantina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJantina As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_MyDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_MyDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTelefon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamat1Daftar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat1Daftar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamat2Daftar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat2Daftar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamat3Daftar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat3Daftar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBandarDaftar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBandarDaftar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlNegeriDaftar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNegeriDaftar As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtPoskodDaftar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPoskodDaftar As Global.System.Web.UI.WebControls.TextBox
End Class
