'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class senarai_permohonan

    '''<summary>
    '''MsgTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''strlbl_top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_top As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblSenaraiPermohonan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSenaraiPermohonan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''MsgBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''strlbl_bottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_bottom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dialogModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dialogModal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hiddenPermohonanID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenPermohonanID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''closeBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents closeBtn As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtNota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNota As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBatalPermohonan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatalPermohonan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTutupModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTutupModal As Global.System.Web.UI.WebControls.Button
End Class
