'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class status_permohonan1

    '''<summary>
    '''permohonanBaharu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanBaharu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''permohonanLayak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanLayak As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''permohonanMenunggu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanMenunggu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''permohonanUnitDicadang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents permohonanUnitDicadang As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''suratTawaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suratTawaran As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mvStatusPermohonan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvStatusPermohonan As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''viewPemohonanDir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPemohonanDir As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblBilAnak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBilAnak As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJenisTempatTinggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenisTempatTinggal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikhMulaMenetap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhMulaMenetap As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKuarterDipohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKuarterDipohon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTarikhPermohonan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikhPermohonan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblMaklumatAnak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMaklumatAnak As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''viewCadanganKuarters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCadanganKuarters As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''MsgTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''strlbl_top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_top As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SaveFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveFunction As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Refresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Refresh As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''tblCadanganKuarters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCadanganKuarters As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''MsgBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''strlbl_bottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strlbl_bottom As Global.System.Web.UI.WebControls.Label
End Class
